name: Build & Push Docker image (GHCR)

on:
  push:
    tags: ["v*"]   # run when you push a tag like v0.0.1

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write   # allows pushing to GHCR with GITHUB_TOKEN
    steps:
      - uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ github.ref_name }}
